---
title: "Example document with some references"
doctype: jou # this can be stu, jou, doc, or man -- try each out!
author: 
  - name: "Justin Dainer-Best"
    affiliation_number: 1
  - name: "Second Author"
    affiliation_number: 2
  - name: "Third Author"
    affiliation_number: "2,3"
  - name: "Fourth Author"
    affiliation_number: 1
affiliations:
  - "Bard College"
  - "Other Institution"
  - "Yet another Institution"
shorttitle: "Example R Markdown APA doc"
leftheader: "Dainer-Best et al."
authors_note: |
  This is an author's note; you could
   remove it if not desired. You 
   could include a corresponding 
   author, and their email. 
abstract: "This is an example of creating an approximately APA-style manuscript using R Markdown and .bib files"
keywords: "LaTeX, RMarkdown, Document formatting"
date: "`r format(Sys.time(), '%B %d, %Y')`" # This print's today's date
output: 
  pdf_document:
    toc_depth: 1
    template: "template.tex"
    keep_tex: true
bibliography: example.bib
link-citations: true
csl: apa.csl
---

# Introduction

This is a simple example of using R Markdown documents to create APA-formatted documents with LaTeX compiling them into PDFs. You will need to install a version of LaTeX to compile; some suggestions are included [here](https://bookdown.org/yihui/rmarkdown-cookbook/install-latex.html) which involve using [TinyTeX](https://yihui.org/tinytex/) [@xie2019]. You may need to install the `apa7` LaTeX package [@weiss2021]; I believe you should be able to do so with `tinytex::tlmgr_install("apa7")` (but I have not yet been able to test this on a machine without a LaTeX installation).

If TinyTeX does not work for you or if you intend to use LaTeX beyond for this work, you may want to install [MacTeX](http://tug.org/mactex/) for Macs or [MiKTeX](https://miktex.org/) for PCs. (These are large installations---thus the point of a "tiny" version.)

You will also have to compile your references in a bibliography. Most folks recommend using Zotero, as do I (manually maintaining references can be frustrating); you'll need to output your references to a .bib file. Document/article titles will follow the capitalization you've got---use APA style yourself! (The most recent versions of R Markdown can also [help add your references](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html), including just from a DOI link.)

Some packages (e.g., {[papaja](https://github.com/crsh/papaja)}; [@austbarth2020]) will create APA-draft manuscripts, but may introduce extra details beyond the basic style. The style I lay out here will simply create a document using APA formatting of references. 

# Getting started

You will need to download the `apa.csl` and `template.tex` documents into a directory where your Rmd file lives. Open (or create) your R Markdown document.

Your document will automatically include some YAML headers:

```
---
title: "Your title"
author: "Your name"
date: "3/29/2021"
output: pdf_document
---
```

You can keep the title and date, but you will need to update the others headers to include some of the following YAML headers in your R Markdown document. In particular, you must include the `doctype`, the full set of `output` parameters (`output: pdf_document: template: "template.tex"`), and the `bibliography` and `csl` lines. The others, including `shorttitle` and `leftheader`, `authors_note`, and so forth, are implemented in APA style documents. 

```
---
doctype: man # this can be stu, jou, doc, or man
title: "Your title"
author: 
  - name: "Your name"
    affiliation_number: 1
affiliations: "Your affiliation"
shorttitle: "APA short title"
authors_note: |
  This is an author's note; 
  you could remove it if not desired. 
abstract: "Your article's abstract"
keywords: "example, keywords"
date: "3/29/21"
output: 
  pdf_document:
    template: "template.tex"
bibliography: example.bib # update to your .bib file!
csl: apa.csl
---
```

A minimal example is included (minimal_example.Rmd and minimal_example.pdf) with these headers; feel free to download it and adapt. Without any changes, it will make the PDF you can see here, so long as you have installed LaTeX---and downloaded the template.tex and apa.csl files into the same directory. 

If you look at example.Rmd, you'll see how to include multiple authors with differing affiliations. List each author separately. Including `affiliation_number` will provide a superscript number after that name, which then anticipates a subsequent item under `affiliations`. (If there are three `affiliation_number`s, there should be three listed `affiliations`.) If an author has multiple affiliations, simply enclose the numbers in quotation marks, as below, separated with a comma: "2,3".

```
author: 
  - name: "First Author"
    affiliation_number: 1
  - name: "Second Author"
    affiliation_number: 2
  - name: "Third Author"
    affiliation_number: "2,3"
  - name: "Fourth Author"
    affiliation_number: 1
affiliations:
  - "First Institution"
  - "Other Institution"
  - "Yet another Institution"
```

As described below, there are some additional headers you may include:

* `leftheader`: The authors' last names (for `jou` doctype only)
* For the `stu` doctype, info about the course: `professor`, `course`, and `duedate`

There are additional YAML headers often used for different documents in R Markdown, many of which may work here. 

# Document types

The **{apa7}** document class in LaTeX accepts four document types---they're mentioned briefly above under `doctype`; you can try each out. Here's what they are:

* _jou_: journal style; intended to mimic what a journal looks like (two columns, etc). This will look weird with the minimal_example file---it looks better with a longer file -- this will also make use of the YAML `leftheader` and `shorttitle`, which will alternate page headers.
* _doc_: a one-column PDF output with APA style (including abstract, etc); it will try to be the "easiest to read"
* _man_: APA's suggestion for how to submit documents to a journal---what many instructors ask for in college course, with double-spacing and so forth
* _stu_: student papers---includes YAML headers `professor`, `course`, and `duedate`; otherwise much like `man`

I've created versions of this Rmd file with each document style, so you can see what they might look like.

# Writing in an R Markdown file

Now that you have a working R Markdown file, you've chosen a document type, and you've updated it with your paper title and name, etc., your focus is on writing the document! 

If you've ever looked into LaTeX document writing, this is more simple. There are three major things to keep in mind:

1. Use \# to start a section, \## to start a subsection, etc.
2. Use square brackets [] to enclose references, e.g., `[@referencekey]`, where you precede a key with the @ symbol. The "reference key" is the way it will be referred in your .bib file---in example.bib, for example, you'll see that it's the first word of each entry. For more info on citations, [see here](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citations).

Most other formatting will be done for you. If you want to learn things about formatting in R Markdown, there are a variety of [cheatsheets](https://rmarkdown.rstudio.com/lesson-15.html) available; you can refer to the example.Rmd document here to learn about links, lists, _italics_ or **bold-face text**, etc.

# Wrapping up

You needn't write anything below the title of your references section---the bibliography will be automatically generated. If you notice that something is inappropriately not capitalized, make sure it is capitalized correctly in your .bib file; if it is, consider surrounding it with curly brackets to ensure

# References

